[#193] fix: failed to load graviton to idea (#194)
### What changes were proposed in this pull request?

change project root name from `Graviton` to `graviton`

### Why are the changes needed?
failed to load project to IDEA
```
java.lang.IllegalStateException: Module entity with name:  graviton should be available
```

Fix: #193 

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Exists UT