[#8861] Improve(test): fix testPolicyAndTagCacheWeigher (#8862)
### What changes were proposed in this pull request?

Bump timeout from 5 seconds to 10 seconds

### Why are the changes needed?

```
TestCacheConfig > testPolicyAndTagCacheWeigher() FAILED
    org.awaitility.core.ConditionTimeoutException: Condition with Lambda expression in org.apache.gravitino.cache.TestCacheConfig was not fulfilled within 5 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
        at app//org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
        at app//org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:975)
        at app//org.apache.gravitino.cache.TestCacheConfig.testPolicyAndTagCacheWeigher(TestCacheConfig.java:162)
```

see failure:
https://github.com/apache/gravitino/actions/runs/18668130387/job/53223578211?pr=8859

Fix: #8861

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Updated unit tests