[#3320] fix(client): shadow slf4j for client-java-runtime  (#3331)
### What changes were proposed in this pull request?
shadow slf4j for client-java-runtime and spark-connector-runtime 

### Why are the changes needed?
some systems like spark 3.3 need low version log4j, will encounter the
conflict bug:

```
java.lang.NoSuchMethodError: org.apache.logging.slf4j.Log4jLoggerFactory: method 'void <init>()' not found
```

fix: #3320 

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
existing tests

Co-authored-by: FANNG <xiaojing@datastrato.com>