[#589] test: add more test failure infomation if test failed. (#859)
### What changes were proposed in this pull request?
1. print more test fail information like stacktrace and cause
```
TestIcebergTableOperations > testUpdateTable() FAILED
    org.opentest4j.AssertionFailedError: expected: <405> but was: <404>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)
        at com.datastrato.gravitino.catalog.lakehouse.iceberg.web.rest.TestIcebergTableOperations.verifyUpdateTableFail(TestIcebergTableOperations.java:106)
        at com.datastrato.gravitino.catalog.lakehouse.iceberg.web.rest.TestIcebergTableOperations.testUpdateTable(TestIcebergTableOperations.java:241)
```
2. upload test report to check more detailed information like in local
machine. we could download the archive in job summary page. like
https://github.com/FANNG1/graviton/actions/runs/7015248449?pr=15



### Why are the changes needed?
Fix: #589 

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
existing UT